image:
  repository: kursova/demoapp
  tag: "8bb4aa88c42a3edb2a8aeddf6ea4b39932be0a8c"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

replicaCount: 1

resources: {}
