image:
  repository: kursova/demoapp
  tag: "a5f6a3dd67e68e83bd48a842212f33ccb8be0460"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

replicaCount: 1

resources: {}
