image:
  repository: kursova/demoapp
  tag: "4828ba39145b7ae73b550127a4b02d34253f84b2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

replicaCount: 1

resources: {}
