image:
  repository: kursova/demoapp
  tag: "f563d4e9efdc3ed1bbeb4492c3b8f062eb5d148e"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

replicaCount: 1

resources: {}
