image:
  repository: kursova/demoapp
  tag: "fddd133846598fdec27f92c40aa113e82ceb03b6"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

replicaCount: 1

resources: {}
