image:
  repository: kursova/demoapp
  tag: "c530a3d871c55a54c075d43b8cdfcb4fbdae0f07"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

replicaCount: 1

resources: {}
