image:
  repository: kursova/demoapp
  tag: "38ace3aa7bd2b758958f06959a0a2e0f3e6426b4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

replicaCount: 1

resources: {}
