image:
  repository: kursova/demoapp
  tag: "5226351a61c1f981cf956fc76cf1537bf211a647"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

replicaCount: 1

resources: {}
