image:
  repository: kursova/demoapp
  tag: "5af90264a591c1b462eca679f531e08d1c15cda3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

replicaCount: 1

resources: {}
