image:
  repository: kursova/demoapp
  tag: "6fa284025554f9075e847c083e9061569f0dd947"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

replicaCount: 1

resources: {}
