image:
  repository: kursova/demoapp
  tag: "e48209b65e47aa4f8416a3c9343c982904d435cf"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

replicaCount: 1

resources: {}
