image:
  repository: kursova/demoapp
  tag: "a54886c26b634926220aba5161ca30ce945e605f"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

replicaCount: 1

resources: {}
