image:
  repository: kursova/demoapp
  tag: "307418c370dd779c9965c6fe40d7e9b3824377d2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

replicaCount: 1

resources: {}
