image:
  repository: kursova/demoapp
  tag: "8f44f02ee8df9da058ba1d283353a685e57c530b"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

replicaCount: 1

resources: {}
