image:
  repository: kursova/demoapp
  tag: "ad28295f3f3c977a662b7b52411d8d708d277a18"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

replicaCount: 1

resources: {}
