image:
  repository: kursova/demoapp
  tag: "e3f0cc78fccf68992df0750ba7e46140367966d5"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

replicaCount: 1

resources: {}
